modLoader="javafml"
loaderVersion="[31,)"
license="GNU General Public License v3.0"
issueTrackerURL="https://github.com/monkeysHK/NoteblockAddons/issues"

[[mods]]
    modId="nbaddons"
    version="1.1"
    displayName="NoteBlock Addons"
    updateJSONURL="https://raw.githubusercontent.com/monkeysHK/NoteblockAddons/update.json"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/noteblock-addons/"
    logoFile="logo.png"
    authors="mhk"
    description='''
    Minecraft 1.16+ Note Block Editting Mod. Makes note block editting simpler and more elegant.
    Credit to CreatorLabs who permitted the use of their designs in this mod.
    '''

[[dependencies.nbaddons]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.nbaddons]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16,1.17)"
    ordering="NONE"
    side="BOTH"
